### ISSUE TITLE
'SkeletonLoading' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by JhosefMatheus** [mmusaib/react-native-skeleton-loading#2]
i did exactly as in the docs:
import SkeletonLoading from 'react-native-skeleton-loading'

const App = () => {

  return(
    <SkeletonLoading background={"#adadad"} highlight={"#ffffff"}>
        <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
          <View style={{ width: 100, height: 100, backgroundColor: "#adadad", borderRadius: 10 }} />

          <View style={{ flex:1, marginLeft: 10 }}>
              <View style={{ backgroundColor: "#adadad", width: "50%", height: 10, marginBottom: 3, borderRadius: 5 }} />
              <View style={{ backgroundColor: "#adadad", width: '20%', height: 8, borderRadius: 5 }} />
              <View style={{ backgroundColor: "#adadad", width: '15%', height: 8, borderRadius: 5, marginTop: 3 }} />
          </View>
        </View>
    </SkeletonLoading>
  )

};

and its sending me the error that i put on title

**Comment by mmusaib** [comment]
Are you using it in bare react-native project or Expo project

**Comment by JhosefMatheus** [comment]
> Are you using it in bare react-native project or Expo project

expo project

**Comment by mmusaib** [comment]
This package is for bare react native, for expo you should use the expo variant of it.

https://github.com/mmusaib/expo-skeleton-loading
